name: CI
on:
  push:
  pull_request:

jobs:
  bench:
    name: ${{ matrix.target }} ${{ matrix.target == 'run_all_attacks' && 'SECRET=' || ''}} ${{ matrix.secret }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] 
        target: [run_all,run_all_attacks]
        secret: [0,1]
        exclude:
          - target: run_all
            secret: 1

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install build-essential cmake iverilog tk binutils-msp430 gcc-msp430 msp430-libc msp430mcu expect-dev verilator -y
      - name: Build sancus-core
        run: mkdir build && cd build && cmake -DNEMESIS_RESISTANT=1 .. && cd ..
      - name: Run test bench
        run: |
          cd core/sim/rtl_sim/run/
          __SECRET=${{ matrix.secret }} ./${{ matrix.target }}
